image:
  file:  .gitpod.dockerfile
  ports:
    - port: 80
tasks:
    - command: mkdir -m 0755 /nix
    - command: chown gitpod /nix
    - command: curl https://nixos.org/nix/install | sh
    - command: git clone https://github.com/git-lfs/git-lfs.git
    - command: cd git-lfs
    - command: make build
    - command: make install
    - command: make build
    - command: make test
    
    
